### ISSUE TITLE
design problems

### ISSUE THREAD

**Issue by polymahh** [muhammadkeyton/ultrawave#3]
the projects are not contained they keep overflowing
- try object-fit = contain if it is possible for mui 
added font poppins in the global style.css, if mui can access it there is no need for font.js

**Comment by polymahh** [comment]
i have the max width for the content at 1140px we need to agree on one
and the mobile layout switch at 700px we need to discuss too

**Comment by polymahh** [comment]
add your circle image like the one am using and put into public folder

**Comment by muhammadkeyton** [comment]
> the projects are not contained they keep overflowing
> 
> * try object-fit = contain if it is possible for mui
>   added font poppins in the global style.css, if mui can access it there is no need for font.js

i have added object-fit:"contain" to the projects and for mui,it cannot access the global css,it only works with it's theme provider.

**Comment by polymahh** [comment]
change the hero image to an illustration
make the navbar mobile responsive
give whole website content 1800px max with
